<?php 
include('dbConnect.php');
//Generated by  sqlParser.py
//Coming from the Client Side i.e from form See output of Ajax Code Generation 
$data = $_POST['data'];
$conn = $pdo->open();
$query='INSERT INTO `Project`(`Id`,`Name`,`UserId`,`ClientId`) VALUES(:projectid,:projectname,:projectuserid,:projectclientid)';
$stmt=$conn->prepare($query);
$stmt->execute(['projectid'=>$data["projectid"],'projectname'=>$data["projectname"],'projectuserid'=>$data["projectuserid"],'projectclientid'=>$data["projectclientid"]]);
$pdo->close();
?>
